/**
 * generated by Xtext
 */
package org.xtext.example.myStateMachines.ui.contentassist;

import org.xtext.example.myStateMachines.ui.contentassist.AbstractMyStateMachinesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyStateMachinesProposalProvider extends AbstractMyStateMachinesProposalProvider {
}
