/*
 * generated by Xtext
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.services.SemcolorGrammarAccess;

public class SemcolorParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SemcolorGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.parser.antlr.internal.InternalSemcolorParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.parser.antlr.internal.InternalSemcolorParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Persons";
	}
	
	public SemcolorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SemcolorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
