grammar org.eclipse.xtext.tutorial.survey.Survey with org.eclipse.xtext.common.Terminals

generate survey "http://www.eclipse.org/xtext/tutorial/survey/Survey"

Main:
	{Main}
	'package' name=STRING
	(imports+=Import)*
	s=Survey
;

Import:
	
	('import' importedNamespace=QualifiedNameWithWildCard 'from'importURI=STRING)
//	('namespace' importedNamespace=QualifiedNameWithWildCard)
;

	
QualifiedNameWithWildCard:
	QualifiedName '.*'?
;
Survey:
	'survey' 
	name=ID 
	title=STRING 
	pages+=Page*;

Page:
	'page' name=ID '('
		questions+=Question*
		followUps+=FollowUp*
	')';

FollowUp:
	'=' Guard? '->' next=[Survey];

Guard:
	
	'HH'
	question=[ChoiceQuestion|QualifiedName]
	'='
	answer=[Choice|QualifiedName]; 

QualifiedName:
	ID ('.' ID)*;

Question:
	FreeTextQuestion | ChoiceQuestion;

FreeTextQuestion:
	'text' name=ID text=STRING;

ChoiceQuestion:
	(single?='single')? 'choice' name=ID text=STRING '(' 
	  choices+=Choice+
	')';	

Choice:
	(freetext?='text')? (name=ID)? text=STRING;