/**
 * generated by Xtext
 */
package org.eclipse.xtext.tutorial.survey.validation;

import org.eclipse.xtext.tutorial.survey.validation.AbstractSurveyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SurveyValidator extends AbstractSurveyValidator {
}
