/*
 * generated by Xtext
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.xtext.example.ui.highlighting.MyCalculator;
import org.xtext.example.ui.highlighting.MyHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SemcolorUiModule extends org.xtext.example.ui.AbstractSemcolorUiModule {
	public SemcolorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return MyCalculator.class;
	}
	
	public Class<? extends DefaultHighlightingConfiguration> bindHighlightingConfiguration() {
		return MyHighlightingConfiguration.class;
	}
}
