/*
 * generated by Xtext
 */
package org.xtext.example.myStateMachines.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.myStateMachines.ui.internal.MyStateMachinesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyStateMachinesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MyStateMachinesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MyStateMachinesActivator.getInstance().getInjector(MyStateMachinesActivator.ORG_XTEXT_EXAMPLE_MYSTATEMACHINES_MYSTATEMACHINES);
	}
	
}
