/*
 * generated by Xtext
 */
package org.xtext.example.myStateMachines.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyStateMachinesUiModule extends org.xtext.example.myStateMachines.ui.AbstractMyStateMachinesUiModule {
	public MyStateMachinesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
