/**
 * generated by Xtext
 */
package org.xtext.example.myStateMachines.validation;

import org.xtext.example.myStateMachines.validation.AbstractMyStateMachinesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyStateMachinesValidator extends AbstractMyStateMachinesValidator {
}
