<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mypackage" nsURI="www.viniovink.com" nsPrefix="hello">
  <eClassifiers xsi:type="ecore:EClass" name="MYclass">
    <eTypeParameters name="dddd"/>
    <eTypeParameters name="derereerddd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="olala" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="[[er bound"/>
</ecore:EPackage>
