/*
 * generated by Xtext
 */
package org.xtext.example.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.services.SemcolorGrammarAccess;

public class SemcolorParser extends AbstractContentAssistParser {
	
	@Inject
	private SemcolorGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.ui.contentassist.antlr.internal.InternalSemcolorParser createParser() {
		org.xtext.example.ui.contentassist.antlr.internal.InternalSemcolorParser result = new org.xtext.example.ui.contentassist.antlr.internal.InternalSemcolorParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGenderAccess().getAlternatives(), "rule__Gender__Alternatives");
					put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
					put(grammarAccess.getNameAccess().getGroup(), "rule__Name__Group__0");
					put(grammarAccess.getPersonsAccess().getPersonsAssignment(), "rule__Persons__PersonsAssignment");
					put(grammarAccess.getPersonAccess().getNameAssignment_0(), "rule__Person__NameAssignment_0");
					put(grammarAccess.getPersonAccess().getGenderAssignment_1(), "rule__Person__GenderAssignment_1");
					put(grammarAccess.getNameAccess().getFirstNameAssignment_0(), "rule__Name__FirstNameAssignment_0");
					put(grammarAccess.getNameAccess().getLastNameAssignment_1(), "rule__Name__LastNameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.ui.contentassist.antlr.internal.InternalSemcolorParser typedParser = (org.xtext.example.ui.contentassist.antlr.internal.InternalSemcolorParser) parser;
			typedParser.entryRulePersons();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SemcolorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SemcolorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
