/*
 * generated by Xtext
 */
package org.xtext.example.mydsl2.ui.labeling

import com.google.inject.Inject
import org.xtext.example.mydsl2.myDsl.Define

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
class MyDslLabelProvider extends org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider {

	@Inject
	new(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	// Labels and icons can be computed like this:
	
	def text(Define ele) {
		ele.name
	}


	
//	def image(Greeting ele) {
//		'Greeting.gif'
//	}
}
