/*
 * generated by Xtext
 */
package org.xtext.example.myStateMachines;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyStateMachinesRuntimeModule extends org.xtext.example.myStateMachines.AbstractMyStateMachinesRuntimeModule {

}
