/*
 * generated by Xtext
 */
package org.xtext.example.myStateMachines;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyStateMachinesStandaloneSetup extends MyStateMachinesStandaloneSetupGenerated{

	public static void doSetup() {
		new MyStateMachinesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

